### ISSUE TITLE
pretrained weights?

### ISSUE THREAD

**Issue by zhoujinhai** [jianing-sun/Mask-YOLO#11]
Hello, Do you have the pretrained weights?

**Comment by Sthem-Pro** [comment]
Hi, no I don't have, please send.

Tried training from scratch and got bad results.

**Comment by zhoujinhai** [comment]
Ok, I don't train now, but I see the issue #1 , you can try to it.

**Comment by Sthem-Pro** [comment]
Thanks, I will try it
