### ISSUE TITLE
Problem with No module named 'mrcnn' when run 

### ISSUE THREAD

**Issue by lovemiffy** [jianing-sun/Mask-YOLO#4]
Hi, I tried to train the model for _rice_ by using _train_rice.py_, but it reports error:

ModuleNotFoundError: No module named 'mrcnn'

in `myolo\model.py` file.

Later, I guessed it may come from the Mask-RCNN project, so I copied the folder `mrcnn` into `myolo` directory, but it reports the same error. (The folder `mrcnn` is part of the project from https://github.com/matterport/Mask_RCNN)

Would you please tell me how to solve it? Thanks for help.

**Comment by Sthem-Pro** [comment]
Hi, I am trying to run this code but the problem is with .h5 file. Can you please share the .h5 file you used. 

I get an error of unequal layers if I load a .h5 file I have,
