### ISSUE TITLE
 This function could not be found.

### ISSUE THREAD

**Issue by WhXl** [jianing-sun/Mask-YOLO#7]
model. py could not find this functionutils.
batch_slice()
Recently, in researching your code, you have done a great project. If it's convenient, please post this code. Thank you.

**Comment by jianing-sun** [comment]
Hi sorry for the late reply. I've just added the code in `myolo_utils.py`. Also, please replace line 644 in `model.py` from `utils.batch_slice` to `mutils.batch_slice`.
